Creating functionality to save data to JSON files
CarlosZ96/-Microverse-School-library pull request #9
Opened 2023-11-03 18:41 UTC by CarlosZ96

The methods are created so that every time we create a new object (person, book and rentals), its information is stored in a JSON file, which in turn will be created when the application is run.

2023-11-03 19:25 UTC, zeff96 reviewed
## STATUS: INVALID CODE REVIEW 🛑
Hi @CarlosZ96 and @jlberbesi , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

📢 Hey @CarlosZ96, it's crucial to highlight that for this milestone to be deemed valid, all partners should actively contribute to the codebase itself. While contributions to the README file are valuable, they aren't considered as direct contributions to the codebase. 📝🚀 So, please take note of this, @jlberbesi!

We kindly request you create a new branch from the 'develop' branch, ensuring equal and substantial contributions to the actual codebase. 🌱🙌 Commit your changes with clear and meaningful commit messages that reflect the purpose and impact of your work. Once done, please submit a Pull Request for review 📥. It's also essential to close the current Pull Request without merging to keep the process streamlined and aligned with our project goals. 🤝 Let's work together for a successful milestone! 🚀👥👍

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-11-03 20:07 UTC, CarlosZ96 commented
Hello @zeff96, I hope you have a good day, I appreciate the time you took to review our code, however, it is important to clarify that in addition to working together on a Zoom call, since I am the one presenting the screen, I suggested doing the code in my commit. This is by mutual agreement, so please do not reject the code, for this reason, we both participate in the creation of the code.

2023-11-03 20:11 UTC, zeff96 commented
Hello @CarlosZ96, I do understand your argument but it does not hold for project being considered as valid, kindly have a look at the project requirements again and be guided accordingly what is accepted as equal contribution. It would be nice for both of you to contribute to the actual codebase while on zoom call and each contribution should reflect on the commit messages

2023-11-03 20:16 UTC, shahadat3669 requested changes
Hi @CarlosZ96, @jlberbesi, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

<img src="https://media1.giphy.com/media/jmqAUNFXAElgafPK0g/giphy.gif"/>

## Invalid Code Review Request

📢 Hey @CarlosZ96, As mentioned by the previous reviewer it's crucial to highlight that for this milestone to be deemed valid, all partners should actively contribute to the codebase itself. While contributions to the README file are valuable, they aren't considered as direct contributions to the codebase. 📝🚀 So, please take note of this, @jlberbesi!

## 🔴🚫Attention🚫🔴 

📢 Your Code Review Request will be marked as invalid🚫 in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

## Have any doubt ❓

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.

<table width="100%" align="center">
  <tr>
    <td colspan="4" align="center">
      <strong>Contact me: Shahadat Hossain</strong>
    </td>
  </tr>
  <tr>
    <td align="center">
      <a href="https://github.com/shahadat3669">
        <img src="https://img.shields.io/badge/github-%23121011.svg?style=for-the-badge&logo=github&logoColor=white" alt="GitHub">
      </a>
    </td>
    <td align="center">
      <a href="https://www.linkedin.com/in/shahadat-cseng/">
        <img src="https://img.shields.io/badge/linkedin-%230077B5.svg?style=for-the-badge&logo=linkedin&logoColor=white" alt="LinkedIn">
      </a>
    </td>
    <td align="center">
      <a href="https://app.slack.com/client/T47CT8XPG/D05GT4E4WAY/rimeto_profile/U04426SD71V">
        <img src="https://img.shields.io/badge/Slack-4A154B?style=for-the-badge&logo=slack&logoColor=white" alt="Slack">
      </a>
    </td>
    <td align="center">
      <a href="mailto:shahadat3669@gmail.com?subject=Microverse%20Code%20Review">
        <img src="https://img.shields.io/badge/Gmail-D14836?style=for-the-badge&logo=gmail&logoColor=white" alt="Email">
      </a>
    </td>
  </tr>
</table>

## ⚠️ WARNING ⚠️

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_**📢💡Invalid Code Review Request **does not count** into the code reviews limit.💡**_

2023-11-04 04:48 UTC, Efiamotu-1 requested changes
Hi @CarlosZ96 & @jlberbesi, 

![](https://user-images.githubusercontent.com/89055502/221963929-dc172827-5c2c-411b-bf4d-923659f626e1.gif) 

Good job so far! 👏. Your Code is Awesome! 💪

There are some **few** issues 🐛 that you still need to work 🔧 on though to go to the next project ⏭️ but you are almost there! 🏃
## Don't Worry 🙏

It's ok to have bugs in your code 🐛. Please, see this code review as a **chance** for you to **learn** practical coding skills and learn **new tips** that can improve your code quality 💯 and help you **get a better ** 💼.

_I am going to guide you on how to fix them down below. 🤓_

## Highlights :dart: 
- ✔️ No linter Errors
- ✔️ Descriptive README
- ✔️ Descriptive PR title and description
- The code is top-notch! 💯 and has a huge potential.

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


## Important Notes 📝

- Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
- Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

> **Note:** Please, don't Merge This Pull Request yet. Only Merge when it is Approved ✅.


## Thank you for your time 🙏 and call me if you need help or clarification ☎️

- This is My **GitHub**: [![@Efiamotu-1](https://img.shields.io/github/followers/Efiamotu-1?label=Habeeb-Efiamotu-Musa&style=social)](https://github.com/Efiamotu-1/)
- This is My **Twitter**: [![@EFYAMOTU](https://img.shields.io/twitter/follow/omarramoun?label=Habeeb-Efiamotu-Musa&style=social)](https://twitter.com/EFYAMOTU)
- This is My **linkedIn**.[![Habeeb Efiamotu Musa](https://img.shields.io/badge/linkedin-@Habeeb-crimson)](https://www.linkedin.com/in/musa-habeeb/)
- This is My **Slack**: [![Habeeb Efiamotu Musa ](https://img.shields.io/badge/slack-@Habeeb-brightgreen)](https://slack.com)

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-11-04 04:48 UTC, Efiamotu-1 commented on main.rb
- [ ] When i try running your code to test your new changes, i am faced with the error below, please kindly look into your codebase and fix it as it important that i am able to run your code so i can test your recently added features :+1: 
![rerp](https://github.com/CarlosZ96/-Microverse-School-library/assets/89055502/73773ed9-c04a-4a6b-a8e6-6fa32e0e62a3)

2023-11-04 04:48 UTC, Efiamotu-1 commented on README.md
>  - Twitter: [@twitterhandle](https://twitter.com/imberbesi)
- [ ] The linkedIn handle provided here is broken please kindly fix it, it is unprofessional to add broken links to your readme file :+1:

2023-11-04 05:01 UTC, jlberbesi commented
@Efiamotu-1 Thanks a lot for your suggestions. I'm working now on it.

2023-11-04 06:31 UTC, abdulhamiid requested changes
# Status: Required Changes :recycle:
Hi Team 🙋‍♂️, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, I really appreciate the effort you put in! but there are still some which haven't been addressed yet.

![almost-there](https://user-images.githubusercontent.com/57562869/143511358-9cde7daf-4ad0-4db2-8f15-18b54288ff91.gif)

## Highlights 🌟

- ✔️ Run a program using the command line
- ✔️ Linters checks are passing
- ✔️ Store data in files.

## Required Changes ♻️
_Please kindly check the comments under the review._

## Optional suggestions 🤷‍♂️
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers, and Happy coding!👏👏👏

## Important Notes 📝
- Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
- Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-11-04 06:31 UTC, abdulhamiid commented on app.rb
> +      @rentals << Rental.new(rental_data['date'], book, person) if book && person
On exit from your app, When I ran the app again, I encountered this error.

![image](https://github.com/CarlosZ96/-Microverse-School-library/assets/78251927/0d646c92-77f3-4c5f-b626-626b0ea775ae)

I checked the saved JSON for rentals and I observed that the issue is according to the name of the retrieved data which should be
`rental_data['person_id'] }` not `rental_data['person']['id'] }`
![image](https://github.com/CarlosZ96/-Microverse-School-library/assets/78251927/670f59d4-4436-49f1-84e5-fab5513c9e09)

Please fix that and ensure that on startup of your app, it loads data from all files🛠🤗

2023-11-04 15:53 UTC, skyv26 approved these changes
## Hi @CarlosZ96, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit:  
Congratulations! 🎉 

## STATUS: APPROVED 🟢 

![](https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExOGJmZWM5NmRjYjQ5ZjZjMjgzYTg1MzRlNDk0MDg5ZTZiM2I3YTk1NSZlcD12MV9pbnRlcm5hbF9naWZzX2dpZklkJmN0PWc/fYlennPcKut8gjKOZD/giphy.gif)

## Highlights
- Implemented the features requested by previous code reviewer ✅ 
 
- Well-structured project ✅ 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

## ⚠️  WARNING ⚠️ 
**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

## Have any doubt ❓ 
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @skyv26 in your question so I can receive the notification. You can also follow me on the below platforms

<table>
<tr>
<td>

<a href="https://github.com/skyv26">
   <img src="https://img.shields.io/badge/GitHub-100000?style=for-the-badge&logo=github&logoColor=white" alt="@skyv26" />
</a>

</td>
<td>

<a href="https://www.linkedin.com/in/skyv2022/">
   <img src="https://img.shields.io/badge/LinkedIn-0077B5?style=for-the-badge&logo=linkedin&logoColor=white" alt="linkedin-skyv2022" />
</a>

</td>
<td>

<a href="https://twitter.com/vrma_aakash">
   <img src="https://img.shields.io/badge/Twitter-1DA1F2?style=for-the-badge&logo=twitter&logoColor=white" alt="@vrma_aakash" />
</a>

</td>
<td>

<a href="https://www.instagram.com/skybrel/">
   <img src="https://img.shields.io/badge/Instagram-E4405F?style=for-the-badge&logo=instagram&logoColor=white" alt="@skybrel" />
</a>

</td>
<td>

<a href="https://www.frontendmentor.io/profile/skyv26">
   <img src="https://user-images.githubusercontent.com/66476329/243158690-61eb1021-fbb6-464d-b841-a09c4caa156e.png" alt="@skybrel" />
</a>

</td>
</tr>
</table>

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-11-04 16:02 UTC, merged